// 389. Find the Difference
// You are given two strings s and t.

// String t is generated by random shuffling string s and then add one more letter at a random position.

// Return the letter that was added to t.

/**
 * @param {string} s
 * @param {string} t
 * @return {character}
 */
var findTheDifference = function(s, t) {
    let charCode = 0;

    for(let i = 0; i < s.length; i++){
        charCode ^= s.charCodeAt(i);
    }
    for(let i = 0; i < t.length; i++){
        charCode ^= t.charCodeAt(i);
    }

    return String.fromCharCode(charCode);
};